services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: administrador
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: game_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
